### ISSUE TITLE
Use new resource & description URIs

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-rdf-to-json#10]
Taking a look at the JSON output, I notice that the URIs haven't changed yet, e.g. this snippet:

``` javascript
{
    "@id": "http://lobid.org/resource/BT000002852",
    "describedby": [
        {
          "@id": "http://lobid.org/resource/BT000002852/about",
          "dateCreated": "19960513",
          "dateModified": "19960513"
        }
    ]
}
```

We decided some time ago to use a hash URI approach with API 2.0 and – because you shouldn't change the extension of a URI – to adjust the URIs a bit. Following this, the JSON should look like this:

``` javascript
{
    "@id": "http://lobid.org/resources/BT000002852#!",
    "describedby": [
        {
          "@id": "http://lobid.org/resources/BT000002852",
          "dateCreated": "19960513",
          "dateModified": "19960513"
        }
    ]
}
```

Note, the `resources` instead of `resource` and the hash bang. (As people weren't satisfied with the "resource" part, we might also switch to something completely different, e.g. `http://lobid.org/cat/BT000002852#!` (for "catalogued thing" and to satisfy with the need of cats on the internet.

**Comment by dr0i** [comment]
+1 for cats!

**Comment by dr0i** [comment]
Deployed to staging, see http://lobid.org/resources-staging/BT000002852.

**Comment by dr0i** [comment]
Pinging also @jschnasse. This may break your apps, please have a look at the new URIs!

**Comment by jschnasse** [comment]
von mir aus

**Comment by acka47** [comment]
+1 pinging @fsteeg because this might also have implications for NWBib.

**Comment by jschnasse** [comment]
Just for documentation

Equal (json data):
http://gaia.hbz-nrw.de:9200/resources/_all/HT018715226/_source
http://lobid.org/resources/HT018715226
http://lobid.org/resources/HT018715226#!

Not Equal
http://gaia.hbz-nrw.de:9200/resources/_all/HT018715226/_source
http://gaia.hbz-nrw.de:9200/resources/_all/HT018715226#!/_source

Reason
The # always stays in browser engine - apache working as proxy will not send it to elasticsearch. http://gaia.hbz-nrw.de:9200/resources/_all/HT018715226#!/_source is interpreted as http://gaia.hbz-nrw.de:9200/resources/_all/HT018715226

**Comment by dr0i** [comment]
ah - right! The `#!/_source` is cut away.

**Comment by fsteeg** [comment]
Looks good in nwbib-staging:

http://test.nwbib.de/BT000002852
http://test.nwbib.de/BT000002854
