### ISSUE TITLE
Only one subject chain makes it into the RDF

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-rdf-to-json#12]
See https://github.com/hbz/lobid-rdf-to-json/blob/bd5a3c54eb050717701a879cc54cdf213276e60a/src/test/resources/output/json/00000/BT000003404.json#L55. The other subject chain from [input, lines 56-57 ](https://github.com/hbz/lobid-rdf-to-json/blob/master/src/test/resources/input/nt/00000/BT000003404.nt#L56-L57) is missing.

**Comment by acka47** [comment]
Here is another example with _four_ subject chains: https://github.com/hbz/lobid-rdf-to-json/blob/b24784bc326f45237c1da78bffbddabc5f6e594d/src/test/resources/output/json/01545/HT015455455.json

**Comment by acka47** [comment]
I guess, at some point people don't want to have order within a subject

**Comment by acka47** [comment]
I don't know how to address this need instead of using different properties `subjectOrder0`, `subjectOrder1`,  [...]

(Comment @dr0i: Why not make rdf-lists in rdf-lists? Needs a little programming, but should be possible.)

**Comment by dr0i** [comment]
See for the solution a [newly created ntriples file](https://github.com/hbz/lobid-rdf-to-json/blob/issue-12-subjectChainsMissing/src/test/resources/input/nt/00000/BT000003404.nt) and the according [new json-ld](https://github.com/hbz/lobid-rdf-to-json/compare/issue-12-subjectChainsMissing#diff-d0937f9cbf85f94a66c2302395915d71L55).
Mind that to be coherent (regarding the field structure) the *Order-fields will _always_ be arrays in arrays, even if there is only _one_ array. That's also true (as discussed) for having only _one_ value in the first array. So the dumbest thing that can occur looks like this::
 `"contributorOrder" : [ [ "http://d-nb.info/gnd/37043-5" ] ]`.
Hope that's fine.

**Comment by acka47** [comment]
> Mind that to be coherent (regarding the field structure) the *Order-fields will _always_ be arrays in arrays, even if there is only _one_ array. That's also true (as discussed) for having only _one_ value in the first array. So the dumbest thing that can occur looks like this::
>  `"contributorOrder" : [ [ "http://d-nb.info/gnd/37043-5" ] ]`.
> Hope that's fine.

I understand that we do it like this for subject order (if we don't decide tomorrow on using a string instead of array for one subject chain) but don't see the need for having arrays in arrays for contributorOrder. There always exists only _one_ contributor order so that one array should be enough.

**Comment by dr0i** [comment]
I would vote against that discrimination beacuse it would a) make the transformation harder and b) presumably make the consumption harder.

> There always exists only one contributor order so that one array should be enough.

Yes, but the same is true for `issued` or `title` where the only one value is served as an array instead of a value directly. So consumers can ever expect the same,  to make consumption as easy as possible. Question is:
is it simpler to consume always arrays in arrays when dealing with ordered lists? Or is it simpler two have to ways to consume ordered lists?

**Comment by acka47** [comment]
As discussed face-to-face we won't use two lists for `contributorOrder`. Whether we want two lists for `subjectOrder` will be discussed on Wednesday. (It might come handy to actually have the `subjectOrder` as a string (e.g. `"subjectOrder: "http://d-nb.info/gnd/4042570-8, Karte"`) to enable easy querying for a subject chain with elasticsearch.)

**Comment by acka47** [comment]
I played around with lists in lists in the JSON playground and it looks like something like the following is not possible in JSON-LD (both arrays being `@lists`):

```javascript
{
  "@id": "http://lobid.org/resource/BT000003404",
  "subjectOrder" : [ [ "http://d-nb.info/gnd/4042570-8", "Karte" ], [ "http://d-nb.info/gnd/4115393-5", "Karte" ] ]
}
```
This isn't a surprise after all, as this isn't even valid _JSON_ (without LD), when you write it in flattened style:

```javascript
{
  "@id": "http://lobid.org/resource/BT000003404",
  "subjectOrder":
  {
    "@list": [ 
      "@list": [ "http://d-nb.info/gnd/4042570-8", "Karte" ],
      "@list": [ "http://d-nb.info/gnd/4115393-5", "Karte" ] 
    ]
  }
}
```

**Comment by acka47** [comment]
I played around with lists in lists in the JSON playground and it looks like what we want isn't possible in JSON-LD (both arrays being `@lists`):

``` javascript
{
  "@id": "http://lobid.org/resource/BT000003404",
  "subjectOrder" : [ [ "http://d-nb.info/gnd/4042570-8", "Karte" ], [ "http://d-nb.info/gnd/4115393-5", "Karte" ] ]
}
```

In flattened style this example would look like this:

``` javascript
{
  "@id": "http://lobid.org/resource/BT000003404",
  "subjectOrder":
  {
    "@list": [ 
      { "@list": ["http://d-nb.info/gnd/4042570-8", "Karte"] },
      { "@list": [ "http://d-nb.info/gnd/4115393-5", "Karte" ] }
    ] }
  }
```

And there we again have "[l]ist of lists in the form of list objects" which "are not allowed in this version of JSON-LD", see also https://github.com/hbz/lobid-resources/issues/4#issuecomment-144336101.

**Comment by dr0i** [comment]
Ok, gonna build a string for `subjectOrder`. Having multiple Strings results in a list. No `lists in lists` needed,then.

**Comment by acka47** [comment]
> Ok, gonna build a string for `subjectOrder`. Having multiple Strings results in a list. No `lists in lists` needed,then.

+1 Just build it like the array but in one string, e.g.: 

``` javascript
{
  "@id" : "http://lobid.org/resource/BT000003404",
  "subjectOrder" : [ "http://d-nb.info/gnd/4042570-8, Karte" , "http://d-nb.info/gnd/4115393-5, Karte" ]
}
```

**Comment by dr0i** [comment]
Just one note, though:
Sometimes there elements of the array are (concatenated) strings, sometimes lonely URIs. See e.g. http://lobid.org/resource/HT013577568/about . Is this fine?

**Comment by acka47** [comment]
I can't see any difference to the example in https://github.com/hbz/lobid-rdf-to-json/issues/12#issuecomment-164406216 where you also have a URI and a string. It's just that we should use another character for seperating the elements of the subject chain if some of these strings contain commas...

**Comment by dr0i** [comment]
See [http://d-nb.info/gnd/4049788-4 in line 71 for subjectOrder of the newly generated json](https://github.com/hbz/lobid-rdf-to-json/commit/e83a9ec917f29b22366f4f829b0bd5bceee781b2#diff-4f944d986404e53f52f23445ace34c22R71). I assumed an URI here since it's just one value (being an URI), better to be seen when [comapring to the corresponding ntriples](https://github.com/hbz/lobid-rdf-to-json/commit/99202b74dc586841c30d0c6de42f9170dcd9c24b) where `"http://d-nb.info/gnd/4076769-3` shows as a URI. Seems that the entries in the json array are always of the same type: strings. Which I thing is fine.

**Comment by dr0i** [comment]
@acka47 do you like the [newly generated json for ordered fields](https://github.com/hbz/lobid-rdf-to-json/commit/e83a9ec917f29b22366f4f829b0bd5bceee781b2#diff-4f944d986404e53f52f23445ace34c22R71)?

**Comment by acka47** [comment]
~~Three~~ Two things: 
1. In https://github.com/hbz/lobid-rdf-to-json/blob/e83a9ec917f29b22366f4f829b0bd5bceee781b2/src/test/resources/output/json/00004/BT000040377.json I see only one string in `subjectOrder` though it should be two (see the [source](http://lobid.org/resource?id=BT000040377&format=source), fields 902 and 907).
2. I don't know whether it is good that `subjectOrder` and `contributorOrder` behave differently. We should discuss this on Wednesday. I see two possible solutions: Using `bibo:contributorList` instead of `lv:contributorOrder` (see also https://github.com/hbz/lobid-resources/issues/4#issuecomment-149890573) and keeping the difference or also storing `contributorOrder` list in a string. However, I prefer number one.

**Comment by acka47** [comment]
> Seems that the entries in the json array are always of the same type: strings. Which I thing is fine.

I concur.

**Comment by dr0i** [comment]
to 1.) : thx for that catch! Fixed it, see e.g. https://github.com/hbz/lobid-rdf-to-json/commit/f50ee8d0d3e2cfe56f5d3c271b50f6768e72268e#diff-8e9c32cfd99a383d707a55d3ce7c6d62L40

**Comment by acka47** [comment]
to 1.): +1

**Comment by acka47** [comment]
Re 2., we do it like this:
- Use `bibo:contributorList` instead of `lv:contributorOrder` (see also https://github.com/hbz/lobid-resources/issues/4#issuecomment-149890573) and keep the representations of the order.
- The context should look something like this:

``` javascript
{
  "@context": {
    "contributorList": {
      "@id": "http://purl.org/ontology/bibo/contributorList",
      "@container": "@list",
      "@type": "@id"
      },
    "subjectOrder": {
      "@id": "http://purl.org/lobid/lv#subjectOrder",
      "@container": "@list"
      }
  }
}
```

**Comment by dr0i** [comment]
@jschnasse is it possible to let `Etikett` produce this:

```
  "@container": "@list",
  "@type": "@id"
```

Can you do this? (I added the entries manually).

**Comment by jschnasse** [comment]
yes I will certainly extend etikett in that way. Until Monday I didn't know of it's existence.

**Comment by acka47** [comment]
What I said in https://github.com/hbz/lobid-rdf-to-json/issues/12#issuecomment-164690950 is _not_ correct. @dr0i pointed me to the fact that there aren't solely contributors with GND in the source but also contributors where we only have a name string. For example [HT018801101](http://lobid.org/resource?id=HT018801101&format=source):

``` xml
 <datafield ind2="1" ind1="-" tag="100">
            <subfield code="p">Arning, Ursula</subfield>
            <subfield code="9">(DE-588)1072011352</subfield>
          </datafield>
          <datafield ind2="1" ind1="a" tag="104">
            <subfield code="a">Kullmer, Bettina</subfield>
          </datafield>
          <datafield ind2="1" ind1="a" tag="108">
            <subfield code="p">Roesner, Elke</subfield>
            <subfield code="9">(DE-588)1049793021</subfield>
          </datafield>
          <datafield ind2="1" ind1="b" tag="112">
            <subfield code="a">Schmitz, Jasmin</subfield>
          </datafield>
```

The difference between string and URI in a `@list` can't be kept in JSON-LD so that we decided to follow the approach anologous to `SubjectOrder` and thus also use `contributorOrder` again as we don't need a list here. This means for this example:

``` javascript
{
  "@context": {
    "contributorOrder": {
      "@id": "http://purl.org/lobid/lv#contributorOrder",
      "@container": "@set",
      },
    "subjectOrder": {
      "@id": "http://purl.org/lobid/lv#subjectOrder",
      "@container": "@list"
      }
  },
  "@id": "http://lobid.org/resources/HT018801101#!",
  "contributorOrder": [ "http://d-nb.info/gnd/1072011352 | Kullmer, Bettina | http://d-nb.info/gnd/1049793021 | Schmitz, Jasmin" ]
}
```

Note that we can't use commas for separating the different entries because they also occur in author names. Thus, we will use pipes. I suggest also using them in `subjectOrder` for the sake of consistency.

**Comment by acka47** [comment]
Looks good now, see http://gaia.hbz-nrw.de:9200/lobid-resources-20160121-145835/json-ld-lobid/_search?q=HT018801101%27. Closing.
