### ISSUE TITLE
Marc relator codes not taken into account for contributorOrder

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-rdf-to-json#14]
See [test file HT006266886.json, lines 3-27](https://github.com/hbz/lobid-rdf-to-json/blob/bd5a3c54eb050717701a879cc54cdf213276e60a/src/test/resources/output/json/00626/HT006266886.json#L3-L27).

**Comment by dr0i** [comment]
After [taking marc relator into account](https://github.com/hbz/lobid-rdf-to-json/compare/issue-12-subjectChainsMissing#diff-eb7afae298fcf4348aa31f821007d77dL24).

**Comment by acka47** [comment]
+1 (except for the double array but I will comment on this in #12)
