### ISSUE TITLE
Add persons and corporate bodies without GND ID to "contributor"/"creator" array

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-rdf-to-json#17]
Will add details and an example as soon as @dr0i has pointed me to a test file that has creator and/or contributors with and without GND ID.

**Comment by dr0i** [comment]
Couldn't find the specification of `lv:contributorOrder`. Want to know:
should there only be contributors or also creators?

**Comment by acka47** [comment]
It should cover `creator`, `contributor` as well as all MARC relators.

**Comment by acka47** [comment]
We must use the same generic property for the label as we do for the other subject, currently this is `gnd:preferredName`. Example:

``` javascript
{
   "@context":"http://lobid.org/download/contextTmp.json",
   "@id":"http://lobid.org/resources/HT018700720#!",
   "contributor":[
      {
         "@id":"http://d-nb.info/gnd/2006655-7",
         "preferredName":"Bundeszentrale für Gesundheitliche Aufklärung",
         "preferredNameForTheCorporateBody":"Bundeszentrale für Gesundheitliche Aufklärung"
      },
      {
         "@id":"http://d-nb.info/gnd/136371671",
         "preferredName":"Amrhein, Ludwig",
         "preferredNameForThePerson":"Amrhein, Ludwig"
      },
      {
         "@id":"http://d-nb.info/gnd/129961604",
         "preferredName":"Heusinger, Josefine",
         "preferredNameForThePerson":"Heusinger, Josefine"
      },
      {
         "@id":"http://d-nb.info/gnd/115325859",
         "preferredName":"Wolter, Birgit",
         "preferredNameForThePerson":"Wolter, Birgit"
      },
      {
         "preferredNameForThePerson": "Ottovay, Kathrin"
      }
   ],
   "contributorOrder":[
      "http://d-nb.info/gnd/136371671 | http://d-nb.info/gnd/129961604 | Ottovay, Kathrin | http://d-nb.info/gnd/115325859 | http://d-nb.info/gnd/2006655-7"
   ]
```

**Comment by acka47** [comment]
I renamed this issue and made a separate one for the alternate labels/variant names, see #24.

**Comment by acka47** [comment]
We should consider typing these entries as `http://d-nb.info/standards/elementset/gnd#UndifferentiatedPerson`. For the example this would look like:

```
{
   "@context":"http://lobid.org/download/contextTmp.json",
   "@id":"http://lobid.org/resources/HT018700720#!",
   "contributor":[
      {
         "preferredNameForThePerson": "Ottovay, Kathrin",
         "@type": "http://d-nb.info/standards/elementset/gnd#UndifferentiatedPerson"
      }
   ]
}
```

**Comment by acka47** [comment]
Re. my last comment. We will use gnd:Person. For the example this results in:

```
{
   "@context":"http://lobid.org/download/contextTmp.json",
   "@id":"http://lobid.org/resources/HT018700720#!",
   "contributor":[
      {
         "preferredNameForThePerson": "Ottovay, Kathrin",
         "@type": "http://d-nb.info/standards/elementset/gnd#Person"
      }
   ]
}
```

With #26 it will just read `Person`.

**Comment by acka47** [comment]
Same for corporate bodies. As https://github.com/hbz/lobid/issues/302 deals with a similar but different problem I am broadening the scope of this issue and adjust the title.

**Comment by dr0i** [comment]
For structural equivalence see also hbz/lobid-rdf-to-json#23.

**Comment by dr0i** [comment]
@acka47 Should the contributors with an id not also typed as gnd:Person? Or should we leave this out for objects with id's?

**Comment by dr0i** [comment]
@acka47 also, what's with a type for contributor as coorporate bodies? Wouldn't this be quite analogous to the forementioned issue with persons? I have in mind to use http://d-nb.info/standards/elementset/gnd#CorporateBody.

**Comment by acka47** [comment]
> Should the contributors with an id not also typed as gnd:Person? Or should we leave this out for objects with id's?

For typing of GND entitites I made a separate issue, see #25 .

> what's with a type for contributor as coorporate bodies?

Please use http://d-nb.info/standards/elementset/gnd#CorporateBody.

**Comment by dr0i** [comment]
Ok.
Deployed to staging, see e.g. http://staging.lobid.org/resources/HT018700720.
With the data now under dct:contributor, maybe we can get rid of `contributorName`?

**Comment by acka47** [comment]
> With the data now under dct:contributor, maybe we can get rid of `contributorName`?

Definitely. I suggest removing deprecated properties after implementing all changes in API 2.0, see https://github.com/hbz/lobid-resources/issues/8.

**Comment by acka47** [comment]
+1
