### ISSUE TITLE
List subjects without GND ID in subject array

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-rdf-to-json#23]
As far as I can see, subjects without GND ID are currently not listed as object without `@id` (i..e. blank node) in the  `subject` array. This probably would make sense for querying etc.

(Just sitting in the DINI AG KIM Titeldaten meeting where this is discussed.)

**Comment by acka47** [comment]
Very similar to #17 which deals with persons without GND ID [edit: and also https://github.com/hbz/lobid/issues/302 which deals with corporate bodies]. Adjusted the title and description to cover subjects.

**Comment by acka47** [comment]
We must use the same generic property for the label as we do for the other subject, currently this is `gnd:preferredName`. Example:

``` javascript
{
   "@context":"http://lobid.org/download/contextTmp.json",
   "@id":"http://lobid.org/resources/TT002234459#!",
   "subject":[
      {
         "@id":"http://d-nb.info/gnd/4114067-9",
         "preferredName":"Jakobsweg",
         "preferredNameForThePlaceOrGeographicName":"Jakobsweg"
      },
      {
         "@id":"http://d-nb.info/gnd/4049787-2",
         "preferredName":"Rhein-Lahn-Kreis",
         "preferredNameForThePlaceOrGeographicName":"Rhein-Lahn-Kreis"
      },
      {
         "@id":"http://dewey.info/class/914/"
      },
       {
         "preferredName":"Karte"
      }
   ],
   "subjectOrder":[
      "http://d-nb.info/gnd/4049787-2, http://d-nb.info/gnd/4114067-9, Karte"
   ]
}
```

**Comment by acka47** [comment]
It might make sense to add the type `gnd:SubjectHeading` to the subjects wihtout GND ID. I am not sure, though.

**Comment by acka47** [comment]
@dr0i When you start working on API 2.0 issues, remember that I created some example files, see https://github.com/hbz/lobid-resources/issues/79#issuecomment-215647251.

**Comment by dr0i** [comment]
But is `subject`  not defined (via the [context](http://lobid.org/download/contextTmp-staging.json)) as 

     	"subject":{
			"@type":"@id",
			"@id":"http://purl.org/dc/terms/subject",

and can, thus, not be a literal (as also the predicate states http://dublincore.org/usage/terms/history/#subjectT-002) ?

**Comment by dr0i** [comment]
> [...] remember that I created some example files,

What shall I do with these - seems to be a whole other issue, no?

**Comment by dr0i** [comment]
Deployed small test set to staging, see e.g. http://staging.lobid.org/resources/TT002234459.

**Comment by acka47** [comment]
+1 looks good, e.g. http://staging.lobid.org/resources/BT000128754. 

The example you link to (http://staging.lobid.org/resources/TT002234459) reminds me that we should consider removing those subject strings from the subject array that we use for type/medium information (i.e. the "Formschlagwörter" like "Karte" and "Aufsatzsammlung"). See also https://github.com/hbz/lobid/issues/54.

**Comment by dr0i** [comment]
Don't know why this was opened again. Closing.
