### ISSUE TITLE
Show objects as strings, not with @id

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-rdf-to-json#28]
From https://github.com/hbz/lobid-resources/issues/27. See 
http://json-ld.org/playground/index.html?startTab=tab-compacted&json-ld={%22%40context%22%3A{%22medium%22%3A{%22%40type%22%3A%22%40id%22%2C%22%40id%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fmedium%22%2C%22label%22%3A%22Tr%C3%83%C2%A4ger%22%2C%22%40container%22%3A%22%40set%22}}%2C%22%40id%22%3A%22http%3A%2F%2Flobid.org%2Fresources%2FBT000168595%22%2C%22medium%22%3A[{%22%40id%22%3A%22http%3A%2F%2Frdvocab.info%2FtermList%2FRDAproductionMethod%2F1010%22}]}&context={%22medium%22%3A{%22%40type%22%3A%22%40id%22%2C%22%40id%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fmedium%22%2C%22label%22%3A%22Tr%C3%83%C2%A4ger%22%2C%22%40container%22%3A%22%40set%22}}
where `medium` is performed without the `@`.

**Comment by acka47** [comment]
Closing. For our decision how to move forward regarding "@type" (using strings mapped to URIs in the context) and other nodes (using objects with label side car) see https://github.com/hbz/lobid-resources/issues/31#issuecomment-188802597.
