### ISSUE TITLE
Implement side car approach

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-rdf-to-json#30]
Using "label" mapped to rdfs:label. For GND resources the labels are taken from the data, for others (e.g. medium) we will use Etikett.

Example:

``` javascript
{
    "@context":{
        "id": "@id",
       "type": "@type",
       "label":"http://www.w3.org/2000/01/rdf-schema#label",
       "subject":{
          "@id":"http://purl.org/dc/terms/subject",
          "@type":"@id"
       },
       "Book": "http://purl.org/ontology/bibo/Book",
       "Thesis": "http://purl.org/ontology/bibo/Thesis"
    },
    "id":"http://lobid.org/resources/HT018881872#!",
    "type":[ "Book", "Thesis" ],
    "medium" : [ {
      "id": "http://rdvocab.info/termList/RDAproductionMethod/1010",
      "label": "Print"
      }
    ],
    "title":[
       "Skateboarding"
    ],
    "otherTitleInformation":[
       "Ethnographie einer urbanen Praxis"
    ],
    "creator":[
       {
          "id":"http://d-nb.info/gnd/103058788",
          "label":"Peters, Christian"
       }
    ],
    "subject":[
       {
          "id":"http://d-nb.info/gnd/4181628-6",
          "label":"Skateboardfahren"
       },
       {
          "id":"http://d-nb.info/gnd/4031483-2",
          "label":"Köln"
       }
    ]
}
```

**Comment by fsteeg** [comment]
I edited creator and subject IDs in the example above to be `id`, not `@id`. That's correct, right?

**Comment by dr0i** [comment]
@fsteeg meanwhile, yes :)

**Comment by dr0i** [comment]
Deployed small test-set, see e.g. http://test.lobid.org/resources/BT000002852.

**Comment by dr0i** [comment]
@acka47 for now only some URIs are configured in https://github.com/hbz/lobid-rdf-to-json/blob/master/src/main/resources/labels.json - in fact I added only `rda:1010`. The additions of data in  https://github.com/hbz/lobid-rdf-to-json/pull/54 results in e.g. `dewey` which was already specified in `labels.json`.
So I suggest you add the objects (medium, nwbib etc.) to `labels.json`.  Then update the tests, build the package and push it. Assign it to me and I will make sure that it's used in `lobid-resources`.

**Comment by acka47** [comment]
It also works for http://purl.org/lobid/rpb, see e.g. http://test.lobid.org/resources/HT018434138#!. I will add nwbib, rpb2 and medium info.

**Comment by acka47** [comment]
> I will add nwbib, rpb2 and medium info.

I will add the two missing nwbib concept schemes as soon as I have the URL for the converter.

Re. the missing medium information as well as the RDF classes we already have in the labels.json we will have to discuss this. Currently the labels for classes are also missing, see e.g. https://github.com/hbz/lobid-rdf-to-json/blob/d615d92cadc951c44d0f5dcaa7b365abad07e338/src/main/resources/labels.json#L12278-L12298. It might be god to be able to import a basic labels file based on an RDF vocabulary like http://purl.org/lobid/lv# but I could also add this manually, though. However, these labels are application-specific and I am quite sure, for example NWBib and Edoweb use different labels for medium/type. Maybe we don't need to add them to the labels.json at all.

**Comment by acka47** [comment]
> However, these labels are application-specific and I am quite sure, for example NWBib and Edoweb use different labels for medium/type.

As the labels.json file is for lobid only, I could add the application-specific (i.e. NWBib-specific) labels.

**Comment by dr0i** [comment]
Deployed to production. Please have a final look @acka47 .

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
Closing.
