### ISSUE TITLE
Implement maven repository

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-rdf-to-json#32]
It's dependency hell, dealing with different version of this libraries without having proper maven repository or git tags. Solutions:
1. incorporate this repo directly into the hbz/lobid-resources repo
2. use git tags or similar
3. provide maven repo to download different versions of dependency

**Comment by fsteeg** [comment]
Two separate thoughts:
1. About a Maven repo: yes, in general a more organized approach to Maven dependencies would be good. Note that we have a Maven repo published on GitHub, see https://github.com/lobid/lobid.github.com and http://lobid.github.io/
2. About the concrete issue here: I really like suggestion 1, i.e. incorporating `lobid-rdf-to-json` into `lobid-resources`. This is a specific converter for the data made available via `lobid-resources` and part of its core functionality, so to me it makes sense that these helper classes should be in `lobid-resources`. It would also save us the overhead of documenting, releasing, etc. a separate repo.

**Comment by dr0i** [comment]
Assign @jschnasse because he's also affected.

**Comment by jschnasse** [comment]
Issue may make sense in itself but:  @dr0i can you describe your concrete issue here? I have the feeling that the solution could be something as simple as adding a parameter to lobid rollout/installation procedure to force installation of a certain tag or branch in you m2.

**Comment by dr0i** [comment]
Concrete description:
With https://github.com/hbz/lobid-rdf-to-json/commit/cb465d237e816d6cdaa806581f95619dec3cd8ed #29 will be resolved. But it's incomaptible with the code running in master in the `lobid-resources` repo, which depends on lobid-rdf-to-json. Now see e.g. hbz/lobid-resources#42 which introduces configurable json-ld contexts.This couldn't be build because at the moment the build uses an install script that goes like:

```
git clone lobid-rdf-to-json
mvn clean install
cd lobid-resources
mvn clean install
```

So after the merge of mentioned https://github.com/hbz/lobid-rdf-to-json/commit/cb465d237e816d6cdaa806581f95619dec3cd8e any building of `lobid-resources` must faill.
1. A workaround is to always use that branch which _is_ compatible with the new `lobid-rdf-to-json`, and to then comment "Merge after #n", see e.g. https://github.com/hbz/lobid-resources/pull/42#issuecomment-189518668. This is possible but it's not nice, as the commits before are not approved and may change and that means rebasing a lot.
2. Also one could configure the mentioned install script to use a special branch for deployment ( a `staging branch`). And to then configure a lobid-resources build to use the staging branch, and if merged, to reconfigure to use the master branch of `lobid-rdf-to-json`. That's awful.

You mentioned `git tags` which I also proposed at the beginning. But that implies to always use a tag in every pull request, no? Also, there is [jgitflow](http://www.sonatype.org/nexus/2015/04/07/maven-release-plugin-setup-guide-for-git-revisited/) . It's overhelming how many possibilities exist. What's the best in the sense of simple and easy with the least effort for everyone?

**Comment by jschnasse** [comment]
Is it possible to modify your install routine to work on a certain revision? e.g.

```
git clone lobid-rdf-to-json
git checkout origin $my-open-pull-request-branch-or-my-recently-tagged-position-or-a-revision-that-is-known-to-work
mvn clean install
```

**Comment by dr0i** [comment]
That I wouldn't know of. How to tell travis, in a reasonable way?
What _does_ work though is the use of release tags on github and jitpack. Just tested it. This means:
1. use git tags in the lobid-rdf-to-json repo
2. in the pom.xml of the consuming project: use jitpack and reference the version.

I found this easy and reasonable enough. It also allows to get rid of the one more `git clone; mvn install`-script workaround thus it becomes more java/git like.

Will document it.

**Comment by jschnasse** [comment]
Ah cool! You don't have to use tags. You can use commit hashes/revisions in your pom . See: https://jitpack.io/ "you can use the short commit hash"

**Comment by fsteeg** [comment]
This would mean adding a dependency to an external service just to manage a dependency that shouldn't even be a separate repo in the first place from my point of view (see https://github.com/hbz/lobid-rdf-to-json/issues/32#issuecomment-190216198).

**Comment by jschnasse** [comment]
Maybe we can start this discussion again, when API 2.0 is close to be productive. In the first place the code in lobid-rdf-to-json comes from regal not from lobid-resources. Separation has been done by me to support lobid. Both projects regal and lobid-resources benefit from the recent development.  In a long perspective I agree with @fsteeg that the code can/should be part of lobid-resources. In fact I would prefer to reuse the code in it's deployed form (over http). For the moment I think this repo is a nice place to work together on the new index format. 
+1 for (easy) jitpack

**Comment by jschnasse** [comment]
@dr0i 

> How to tell travis, in a reasonable way?

Instead of using jitpack you could simply introduce a variable `$a-revision-that-works`  in your .travis.conf
     git clone lobid-rdf-to-json
     git checkout origin $a-revision-that-works
     mvn clean install

**Comment by dr0i** [comment]
@jschnasse  _Would_ work, but ,used to configure dependencies in pom, I would find this a bit obscure. Also, at your desktop, I (and IDE) just do `mvn clean install` and not executing some script before. I imagine running into confusion soon enough. Better KISS.

**Comment by dr0i** [comment]
> You can use commit hashes/revisions in your pom .

Thx for making me aware! I was going to use github releases, but using commit hashes is a _really_ nice solution :)

**Comment by dr0i** [comment]
As we all agreed offline we will use jitpack for now. Updated the README in [lobid-resources repo](https://github.com/hbz/lobid-resources) for a how-to, see https://github.com/hbz/lobid-resources/commit/fb185285c25f91f3de60c0d11549653082625613#diff-8aa641a619b8ebeca0116d41774daf45R62 .
