### ISSUE TITLE
Classes in context with superfluous @type/@container info

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-rdf-to-json#59]
The classes in the lobid-resources JSON-LD context are not shown as expected. Example:

```json
"MultiVolumeBook":{
   "@type":"@id",
   "@id":"http://purl.org/ontology/bibo/MultiVolumeBook",
   "@container":"@set"
},
"Newspaper":{
   "@type":"@id",
   "@id":"http://purl.org/ontology/bibo/Newspaper",
   "@container":"@set"
},
"Game":{
   "@type":"@id",
   "@id":"http://purl.org/library/Game",
   "@container":"@set"
}
```

The `@type` and `@container` information doesn't make any sense on an `owl:Class`. It should instead just read:

```json
"MultiVolumeBook": "http://purl.org/ontology/bibo/MultiVolumeBook",
"Newspaper": "http://purl.org/ontology/bibo/Newspaper",
"Game": "http://purl.org/library/Game"
```

**Comment by acka47** [comment]
For the labels.json this means that `"uri"` and `"name"` would be sufficient:

```json
    {
        "uri": "http://purl.org/ontology/bibo/MultiVolumeBook",
        "name": "MultiVolumeBook"
    },
    {
        "uri": "http://purl.org/ontology/bibo/Newspaper",
        "name": "Newspaper"
    },
    {
        "uri": "http://purl.org/library/Game",
        "name": "Game"
    }
```

**Comment by dr0i** [comment]
I would like to have a field which would show if it's about a `property` or a `class`. This would really make things clearer.

**Comment by acka47** [comment]
> I would like to have a field which would show if it's about a `property` or a `class`.

We could use `type` for this. (I think it is not used in labels.json yet.). E.g.:

```json
    {
        "uri": "http://purl.org/ontology/bibo/MultiVolumeBook",
        "name": "MultiVolumeBook",
        "type": "Class"
    },
    {
        "uri": "http://purl.org/ontology/bibo/Newspaper",
        "name": "Newspaper",
        "type": "Class"
    },
    {
        "uri": "http://purl.org/library/Game",
        "name": "Game",
        "type": "Class"
    }
```

**Comment by acka47** [comment]
So, I just tried out what I wrote in https://github.com/hbz/lobid-rdf-to-json/issues/59#issuecomment-262207246 removing this from some classes in the labels.json:

```json
        "referenceType": "@id",
        "container": "@set",
        "multilangLabel": { }
```

Running mvn test the results were pretty strange. Although errors where thrown it said "Built success" as no tests failed. In the context the classes I had adjusted in labels.json were missing.

**Comment by acka47** [comment]
I think this issue should be fixed before the launch. I thought about moving it to the lobid-resources repo but as we already have some discussion here, this doesn't make sense imo.

**Comment by jschnasse** [comment]
Just trying to catch up with current status in lobid-resources. Since you already have added the capability to load directories with multiple label files - so you already separated context data from additional labels data. I'd suggest to simply support json-ld context format directly in addition, e.g. using something like https://github.com/hbz/etikett/blob/master/app/helper/EtikettMaker.java#L348 and add the resulting list to the internal Map for further processing within the JsonConverter.
A possible convention could be to provide exactly one file under /labels with the name context.json plus an arbitrary number of additional label files for e.g. dewey, rplb, etc. Maybe @dr0i can implement best?

**Comment by acka47** [comment]
> so you already separated context data from additional labels data

We could but haven't yet. Opened an issue for this, see https://github.com/hbz/lobid-resources/issues/310
