### ISSUE TITLE
Use correct JSON-LD keywords (with '@') for context

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-rdf-to-json#70]
Currently, our JSON-LD is broken when pasted into the [JSON-LD playground](http://json-ld.org/playground/). The error message reads:

> "name": "jsonld.SyntaxError",
  "message": "Invalid JSON-LD syntax; an @context @type value must be an absolute IRI.",

The problem is the use of `id` instead of `@id` in the context, e.g.

```json
       "Creator": {
        "@type": "id",
        "@id": "http://id.loc.gov/vocabulary/relators/cre",
        "@container": "@set"
      }
```

The incorrect `id`s should be replaced. Note that, this currently only affects classes which should not have any `@type` information at all, see #59.

**Comment by fsteeg** [comment]
Note that the actual context now is in `lobid-resources-web` (see https://github.com/hbz/lobid-resources-web/pull/9#issuecomment-269334892, https://github.com/hbz/lobid-resources-web/blob/master/conf/context.jsonld).
