### ISSUE TITLE
In labels.json use "referenceType" only on properties

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-rdf-to-json#9]
It's at least confusing to have `referenceType` also set on `skos:Concept`. Even more confusing, that DDC concepts and RPB classification concepts don't shar ethe same `referenceType`. See for example:

``` javascript
    {
        "uri":"http://dewey.info/class/828/",
        "label":"Englische vermischte Schriften",
        "referenceType":"class"
    }
```

vs.

``` javascript
    {
        "uri":"http://purl.org/lobid/rpb#n262014",
        "label":"Schanze",
        "referenceType":"http://www.w3.org/2004/02/skos/core#Concept"
    }
```

The best solution would be if `referenceType` would only be used on properties.

**Comment by jschnasse** [comment]
Current master should do the trick. Please set "String" type explicit to get entries included into context.
Please reload your database by downloading labels.json and reingesting it via "add New" / POST.
https://github.com/hbz/etikett/commit/c5eed911c2e09b79156a80c8b1a2f9c7b2e78a14
